name: videoz
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  bot_toast: ^4.0.3
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  video_player: ^2.5.3
  path_provider: ^2.0.13
  video_thumbnail: ^0.5.3
  shimmer: ^2.0.0
  get_it: ^7.2.0
  flex_color_scheme: ^6.1.2
  wechat_assets_picker: ^8.4.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.0.5
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
